### ISSUE TITLE
including shapes-polyfill.js in wordpress

### ISSUE THREAD

**Issue by willy-george** [adobe-webplatform/css-shapes-polyfill#14] opened 2015-06-18 08:37 UTC
dear developers,

thanks for your great work.
i would like to include the shapes-polyfill.js in wordpress. i put it in the footer.php of my theme, it does not work properly. it seems that the script is not answering, so i must stop manually.

browser in use is ff 38.0.5

downloaded demos from your platform are looking well, there are no javascript-problems.

i would be very pleased, if you could help.

thank you so much. 

regards
willy-george

**Comment by oslego** [comment] 2015-06-30 10:57
@willy-george you'll need to be more specific as to what the problem is. 

Have you carefully read the [README.md](https://github.com/adobe-webplatform/css-shapes-polyfill/blob/master/README.md) file for instructions on how to use the polyfill?

**Comment by iankroll** [comment] 2015-12-07 18:11
Have you found a solution for this? shapes-polyfill.js definitely does not work with Wordpress. When I add it to my site, it consistently causes Firefox to completely crash with a message like:
"A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to ..."
Not sure if this matters, but I am using the "Responsive" theme from Cyberchimps.
My client sure would like me to get this going, any help would be greatly appreciated!

**Comment by oslego** [comment] 2015-12-08 10:05
@iankroll, please provide a reduced test case (a small example file which shows the problem) so that we can investigate the issue. There may very well be an unintended interaction with some other part of the theme; you need to find and isolate that.

Also, please be aware that this polyfill isn't meant to be used on production. It's not being actively maintained anymore.

**Comment by iankroll** [comment] 2015-12-09 18:41
thank you very much for the response, I really appreciate that. I could show you a simple WordPress test site on my server that exhibits the issue, would that be OK?. I happens whenever the polyfill is included and any content on the page uses the .curve class.

you mention it is no longer maintained ... is there a newer way of accomplishing the same thing?

Once again, thank you VERY much for the response

**Comment by oslego** [comment] 2015-12-10 09:42
If you think one specific element with its styles is causing the problems, please isolate the code in a simple page to highlight the issue.

Regarding maintenance, it's reasonable to expect that this polyfill will stop functioning at one point. Your code should be built with progressive enhancement in mind. Browsers like Chrome and Safari support CSS Shapes natively. For the browsers which don't, the page should not break. A polyfill should not be _required_ for the page to function properly. It's ok for the page to look different.

**Comment by iankroll** [comment] 2015-12-11 00:40
thanks. I've been trying to make the page behave as nicely as possible when not viewed in Chrome or Safari, but it would be NICE is I could get the polyfill to work.

The issue seems to arise when one of my css classes uses -webkit-shape-outside:circle();

I will try to get a simple example set up and let you know once I've done that

**Comment by iankroll** [comment] 2015-12-18 01:20
I have a brand new wordpress installation, with the default theme and no plugins installed. The polyfill still exhibits the same issue. You can see the site at:
http://162.213.156.67/~sftscrew/
this works. But if you go to this page (where I included the polyfill) it crashes firefox:
http://162.213.156.67/~sftscrew/polyfill
I appreciate the advice you've given me so far. I'm hoping you will have some insight as to how I might fix this! Thanks

**Comment by iankroll** [comment] 2016-01-15 05:34
oh jeez, I just realized that domain is no longer valid. My examples are at:
http://sftscrew.com/
and
http://sftscrew.com/polyfill/

**Comment by oslego** [comment] 2016-03-06 16:40
I tested your polyfill example in the latest release of stable Firefox 44 and it doesn't seem to crash the page.
<img width="2032" alt="screen shot 2016-03-06 at 4 28 31 pm" src="https://cloud.githubusercontent.com/assets/63899/13555471/191d43de-e3b9-11e5-89b6-02dff361a72b.png">

I'm closing this issue for now. 

Going forward, I do not recommend using this polyfill. Instead, use [Feature Queries in CSS](https://developer.mozilla.org/en/docs/Web/CSS/@supports) to detect if CSS shapes are supported and use the native browser implementation. It will be much faster and you'll avoid many more bugs as this polyfill is no longer actively maintained.

Use as follows:

``` css
@supports ( shape-outside: circle() ) or ( -webkit-shape-outside: circle() ){
  .curve{
    -webkit-shape-outside: circle();
    shape-outside: circle();
  }
}
```

If other browsers decide to support CSS Shapes in the future (Edge, Firefox), it is unlikely that they will do so with a prefix (using feature flags seem to have become the norm) so you won't have to include all known prefixed variation in that feature query.

**Closed as completed by oslego** 2016-03-06 16:40 UTC

**Comment by iankroll** [comment] 2016-03-08 17:00
Oh wow, I can't believe that is working on that test page! I'm not sure what changed. I had given up on that and was working on other aspects of the javascript used on the site. Perhaps I inadvertently fixed an incompatibility.
Thank you for you advice on using "@supports". That is something I did not know about before. I guess you learn something new every day!
Thanks for your help you gave me with this, it is much appreciated.

**Comment by little-burrito** [comment] 2018-01-30 20:00
I've just run into the same issue, and I eventually found that it only occurs when you are logged in (so the admin bar is visible at the top of the page). Unfortunately I don't have time to investigate this further at the moment, and I can live with this result for now.
